[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[workspace]
members = ["programs/sol-backend"]

[features]
resolution = true
skip-lint = false
seeds = false
custom-heap = false

[programs.localnet]
sol-backend = "C3xL6yYf9jyCJfthRE2nWYeLS1RLDkaDnUf2zcrGYtMj"

[programs.devnet]
sol-backend = "C3xL6yYf9jyCJfthRE2nWYeLS1RLDkaDnUf2zcrGYtMj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
