[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false
seeds = false
custom-heap = false

[programs.localnet]
sol_backend = "DGVR8rFF2XAwdihMwjH5WsmyqQfhzU5ZTi4bjiy3Jwwx"

[programs.devnet]
sol_backend = "DGVR8rFF2XAwdihMwjH5WsmyqQfhzU5ZTi4bjiy3Jwwx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
