[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
sol_backend = "HpEWLU7hUuDasqiVvZaL6bQAnyUTY9SUhHWTL9uz4kc4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
